// Code generated by baton-sdk. DO NOT EDIT!!!
package batonconfig

import "reflect" 

type Batonconfig struct {
	ServiceProvider string `mapstructure:"service-provider"`
	ScimConfig string `mapstructure:"scim-config"`
	ApiKey string `mapstructure:"api-key"`
	Username string `mapstructure:"username"`
	Password string `mapstructure:"password"`
	ScimClientId string `mapstructure:"scim-client-id"`
	ScimClientSecret string `mapstructure:"scim-client-secret"`
	ScimConfigFile string `mapstructure:"scim-config-file"`
	AccountId string `mapstructure:"account-id"`
	ScimConfigValue string `mapstructure:"scim-config-value"`
}

func (c *Batonconfig) findFieldByTag(tagValue string) (any, bool) {
	v := reflect.ValueOf(c).Elem() // Dereference pointer to struct
	t := v.Type()

	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		tag := field.Tag.Get("mapstructure")

		if tag == tagValue {
			return v.Field(i).Interface(), true
		}
	}
	return nil, false
}

func (c *Batonconfig) GetStringSlice(fieldName string) []string {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return []string{}
	}
	t, ok := v.([]string)
	if !ok {
		panic("wrong type")
	}
	return t
}

func (c *Batonconfig) GetString(fieldName string) string {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return ""
	}
	if t, ok := v.(string); ok {
		return t
	}
	if t, ok := v.([]byte); ok {
		return string(t)
	}
	panic("wrong type")
}

func (c *Batonconfig) GetInt(fieldName string) int {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return 0
	}
	t, ok := v.(int)
	if !ok {
		panic("wrong type")
	}
	return t
}

func (c *Batonconfig) GetBool(fieldName string) bool {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return false
	}
	t, ok := v.(bool)
	if !ok {
		panic("wrong type")
	}
	return t
}

func (c *Batonconfig) GetStringMap(fieldName string) map[string]any {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return map[string]any{}
	}
	t, ok := v.(map[string]any)
	if !ok {
		panic("wrong type")
	}
	return t
}
