apiEndpoint: "https://${SAP_SF_API_SERVER}/successfactorsfoundation/rest/iam/scim/v2" # Example for sandbox: "https://sandbox.api.sap.com/successfactorsfoundation/rest/iam/scim/v2"
hasScimHeader: true
auth:
  authType: "customTokenSource"
  apiKeyPrefix: "Bearer"
  authUrl: "REPLACE_WITH_PROD_AUTH_URL" # Example for sandbox: "https://sandbox.api.sap.com/oauth/token?grant_type=client_credentials"
  tokenPath: "access_token"
  withCustomTokenRequest: true
  tokenRequestDefaults:
    contentType: "application/x-www-form-urlencoded"
    formBodyValues:
      grant_type: "urn:ietf:params:oauth:grant-type:saml2-bearer"
      client_id: "REPLACE_WITH_CLIENT_ID"
      assertion: "REPLACE_WITH_SAML_ASSERTION"
      company_id: "REPLACE_WITH_COMPANY_ID"
user:
  id: "id"
  userName: "userName"
  displayName: "displayName"
  firstName: "name.givenName"
  lastName: "name.familyName"
  active: "active"
  skipUserEmails: true
  hasGroupsOnUser: true
  userGroup:
    id: "value"
    name: "display"
    path: "groups"
group:
  id: "value"
  displayName: "display"
pagination:
  totalResults: "totalResults"
  itemsPerPage: "count"
  startIndex: "startIndex"
provisioning:
  addUserToGroup:
    schemas: "urn:ietf:params:scim:api:messages:2.0:PatchOp"
    op: "add"
    path: "members"
    valuePath: "value"
  removeUserFromGroup:
    schemas: "urn:ietf:params:scim:api:messages:2.0:PatchOp"
    op: "remove"
    path: "members"
    valuePath: "value"