name: ci
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Run linters
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout=3m
  go-test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: go tests
        run: go test -v -covermode=count -json ./... > test.json
      - name: annotate go tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.6.0
        with:
          test-results: test.json
  test-slack:
    runs-on: ubuntu-latest
    needs:
      - go-lint
      - go-test
    env:
      BATON_API_KEY: ${{ secrets.USER_SLACK_OAUTH_TOKEN }}
      BATON_SERVICE_PROVIDER: slack
      BATON_LOG_LEVEL: debug
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Build baton-scim
        run: go build ./cmd/baton-scim

      - name: Test grant/revoke
        uses: ConductorOne/github-workflows/actions/sync-test@v2
        with:
          connector: ./baton-scim
          baton-entitlement: group:S06MUM6GEPM:member
          baton-principal: U06R7AC1BM1
          baton-principal-type: user
      - name: Sync SCIM Slack
        run: ./baton-scim --service-provider=slack
